# Generated by Django 4.0.1 on 2022-03-11 19:33

import changes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changes', '0002_rename_year_in_school_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nvd_checksum',
            field=models.CharField(default=changes.models.get_random_sha256, max_length=64, unique=True),
        ),
    ]
