# Generated by Django 4.0.1 on 2022-02-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_delete_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("name", "vendor_id"), name="ix_unique_products"
            ),
        ),
    ]
